### ISSUE TITLE
Readme contains invalid example

### ISSUE THREAD

**Issue by gschwaer** [thomaseizinger/keep-a-changelog-new-release#16]
Hi, the readme shows
```
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        tag: v0.6.0 # You probably want to have this dynamic :)
```
But this will load the action from branch `v1` which is `1.2.1` which does not have a `tag` parameter and requires a `version` parameter. So using the example as it is you'll get:
```
Error: Input required and not supplied: version
```
The fix is probably to ff merge the `v1` branch to `master`, if there is no urgent reason to keep it on `1.2.1`. Thx
