### ISSUE TITLE
Dog food the action

### ISSUE THREAD

**Issue by thomaseizinger** [thomaseizinger/keep-a-changelog-new-release#5]
Add a CI config where we use our own action :)

**Comment by joesturge** [comment]
wouldn;t something like this work if you create a `.github/workflows/release.yaml`

```yaml
...
      - name: Update changelog
        id: update_changelog
        uses: ./
        with:
          tag: ${{ github.ref_name }}
...
```
